In [72]:
import pandas as pd
import numpy as np

df = pd.read_csv("Travel details dataset.csv")

print(df.head())

   Trip ID       Destination Start date   End date  Duration (days)  \
0        1        London, UK   5/1/2023   5/8/2023              7.0
1        2  Phuket, Thailand  6/15/2023  6/20/2023              5.0
2        3   Bali, Indonesia   7/1/2023   7/8/2023              7.0
3        4     New York, USA  8/15/2023  8/29/2023             14.0
4        5      Tokyo, Japan  9/10/2023  9/17/2023              7.0

   Traveler name  Traveler age Traveler gender Traveler nationality  \
0     John Smith          35.0            Male             American
1       Jane Doe          28.0          Female             Canadian
2      David Lee          45.0            Male               Korean
3  Sarah Johnson          29.0          Female              British
4     Kim Nguyen          26.0          Female           Vietnamese

  Accommodation type Accommodation cost Transportation type  \
0              Hotel               1200              Flight
1             Resort                800              Flight
2              Villa               1000              Flight
3              Hotel               2000              Flight
4             Airbnb                700               Train

  Transportation cost
0                 600
1                 500
2                 700
3                1000
4                 200

In [73]:
print(df.isnull().sum())

Trip ID                 0
Destination             2
Start date              2
End date                2
Duration (days)         2
Traveler name           2
Traveler age            2
Traveler gender         2
Traveler nationality    2
Accommodation type      2
Accommodation cost      2
Transportation type     3
Transportation cost     3
dtype: int64

In [74]:
missing_values = df.isnull().sum()

print("Missing Values:")
display(missing_values)

Missing Values:

Trip ID                 0
Destination             2
Start date              2
End date                2
Duration (days)         2
Traveler name           2
Traveler age            2
Traveler gender         2
Traveler nationality    2
Accommodation type      2
Accommodation cost      2
Transportation type     3
Transportation cost     3
dtype: int64

In [75]:
print("Duplicate rows:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Duplicate rows after removal:", df.duplicated().sum())

print(df.head())

Duplicate rows: 0
Duplicate rows after removal: 0
   Trip ID       Destination Start date   End date  Duration (days)  \
0        1        London, UK   5/1/2023   5/8/2023              7.0
1        2  Phuket, Thailand  6/15/2023  6/20/2023              5.0
2        3   Bali, Indonesia   7/1/2023   7/8/2023              7.0
3        4     New York, USA  8/15/2023  8/29/2023             14.0
4        5      Tokyo, Japan  9/10/2023  9/17/2023              7.0

   Traveler name  Traveler age Traveler gender Traveler nationality  \
0     John Smith          35.0            Male             American
1       Jane Doe          28.0          Female             Canadian
2      David Lee          45.0            Male               Korean
3  Sarah Johnson          29.0          Female              British
4     Kim Nguyen          26.0          Female           Vietnamese

  Accommodation type Accommodation cost Transportation type  \
0              Hotel               1200              Flight
1             Resort                800              Flight
2              Villa               1000              Flight
3              Hotel               2000              Flight
4             Airbnb                700               Train

  Transportation cost
0                 600
1                 500
2                 700
3                1000
4                 200

In [76]:
df["Start date"] = pd.to_datetime(
    df["Start date"],
    errors="coerce"
)

df["End date"] = pd.to_datetime(
    df["End date"],
    errors="coerce"
)

print(df[["Start date", "End date"]].head())

  Start date   End date
0 2023-05-01 2023-05-08
1 2023-06-15 2023-06-20
2 2023-07-01 2023-07-08
3 2023-08-15 2023-08-29
4 2023-09-10 2023-09-17

In [77]:
df["Accommodation cost"] = pd.to_numeric(
    df["Accommodation cost"],
    errors="coerce"
)

df["Transportation cost"] = pd.to_numeric(
    df["Transportation cost"],
    errors="coerce"
)

print(df[
    [
        "Accommodation cost",
        "Transportation cost"
    ]
].head())

   Accommodation cost  Transportation cost
0              1200.0                600.0
1               800.0                500.0
2              1000.0                700.0
3              2000.0               1000.0
4               700.0                200.0

In [78]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Trip ID               139 non-null    int64
 1   Destination           137 non-null    str
 2   Start date            137 non-null    datetime64[us]
 3   End date              137 non-null    datetime64[us]
 4   Duration (days)       137 non-null    float64
 5   Traveler name         137 non-null    str
 6   Traveler age          137 non-null    float64
 7   Traveler gender       137 non-null    str
 8   Traveler nationality  137 non-null    str
 9   Accommodation type    137 non-null    str
 10  Accommodation cost    72 non-null     float64
 11  Transportation type   136 non-null    str
 12  Transportation cost   71 non-null     float64
dtypes: datetime64[us](2), float64(4), int64(1), str(6)
memory usage: 14.2 KB
None

In [79]:
numeric_columns = [
    "Duration (days)",
    "Traveler age",
    "Accommodation cost",
    "Transportation cost"
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

In [80]:
categorical_columns = [
    "Destination",
    "Traveler gender",
    "Traveler nationality",
    "Accommodation type",
    "Transportation type"
]

for col in categorical_columns:
    df[col] = df[col].fillna("Unknown")

In [81]:
df["Start date"] = df["Start date"].fillna(
    df["Start date"].mode()[0]
)

df["End date"] = df["End date"].fillna(
    df["End date"].mode()[0]
)

In [82]:
df["Total Trip Cost"] = (
    df["Accommodation cost"] +
    df["Transportation cost"]
)

display(
    df[
        [
            "Trip ID",
            "Destination",
            "Accommodation cost",
            "Transportation cost",
            "Total Trip Cost"
        ]
    ].head()
)

,Trip ID,Destination,Accommodation cost,Transportation cost,Total Trip Cost
0,1,"London, UK",1200.0,600.0,1800.0
1,2,"Phuket, Thailand",800.0,500.0,1300.0
2,3,"Bali, Indonesia",1000.0,700.0,1700.0
3,4,"New York, USA",2000.0,1000.0,3000.0
4,5,"Tokyo, Japan",700.0,200.0,900.0

In [83]:
Q1 = df["Total Trip Cost"].quantile(0.25)

Q3 = df["Total Trip Cost"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR

upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Total Trip Cost"] < lower) |
    (df["Total Trip Cost"] > upper)
]

print("Total Trip Cost Outliers:")

display(
    outliers[
        [
            "Trip ID",
            "Destination",
            "Duration (days)",
            "Total Trip Cost"
        ]
    ]
)

Total Trip Cost Outliers:

     Trip ID                  Destination  Duration (days)  Total Trip Cost
1          2             Phuket, Thailand              5.0           1300.0
3          4                New York, USA             14.0           3000.0
4          5                 Tokyo, Japan              7.0            900.0
5          6                Paris, France              5.0           2300.0
7          8       Rio de Janeiro, Brazil              7.0           1500.0
8          9       Amsterdam, Netherlands              7.0           1400.0
9         10  Dubai, United Arab Emirates              7.0           3300.0
10        11               Cancun, Mexico              7.0           1500.0
11        12             Barcelona, Spain              7.0            900.0
12        13             Honolulu, Hawaii              8.0           4200.0
13        14              Berlin, Germany              9.0           2100.0
14        15           Marrakech, Morocco              7.0           1000.0
15        16          Edinburgh, Scotland              7.0           1050.0
38        39                Paris, France              7.0           2000.0
39        40            Sydney, Australia              7.0            950.0
40        41                 Tokyo, Japan              8.0           1400.0
41        42               Cancun, Mexico              7.0           3000.0
43        44                   London, UK              7.0           1000.0
44        45             Barcelona, Spain              7.0           1200.0
45        46           New York City, USA              7.0           2000.0
46        47            Bangkok, Thailand              6.0            550.0
47        48            Vancouver, Canada              7.0            550.0
60        61                        Paris              6.0           2000.0
61        62                        Tokyo              7.0            700.0
62        63                    Cape Town              9.0           1000.0
63        64                       Sydney              6.0           2700.0
65        66                         Bali              7.0           3200.0
66        67                        Paris              6.0           1300.0
68        69                      Bangkok              8.0           1000.0
69        70                         Rome              6.0           1400.0
70        71                         Bali              8.0           2800.0
82        83                  Rome, Italy              7.0            800.0
106      107                        Tokyo              9.0           1300.0
107      108                     New York              5.0           1400.0
108      109                         Bali              8.0           2700.0
109      110                       Sydney              9.0           1200.0
110      111                       London              5.0           1050.0
111      112                       Phuket              7.0           2700.0
112      113                         Rome              7.0           1350.0
113      114                    Santorini              7.0           1150.0
115      116                   Phnom Penh              5.0            700.0
119      120                  Rome, Italy              7.0           1300.0
120      121              Bali, Indonesia             10.0           1300.0
125      126                Paris, France              8.0           1100.0
128      129                Paris, France              6.0           7500.0
129      130                 Tokyo, Japan              7.0           8500.0
130      131      Cape Town, South Africa              9.0           5000.0
131      132            Sydney, Australia              6.0           9000.0
132      133                  Rome, Italy              7.0           5500.0
133      134           New York City, USA              7.0          10500.0
134      135       Rio de Janeiro, Brazil              9.0           4500.0
135      136            Vancouver, Canada              6.0           8000.0
136      137            Bangkok, Thailand              7.0           3000.0
137      138             Barcelona, Spain              7.0           8500.0
138      139        Auckland, New Zealand              7.0           9500.0

In [84]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

print("MinMaxScaler imported successfully")

MinMaxScaler imported successfully

In [85]:
num_cols = [
    "Duration (days)",
    "Traveler age",
    "Accommodation cost",
    "Transportation cost"
]

scaler = MinMaxScaler()

df[num_cols] = scaler.fit_transform(df[num_cols])

print(df.head())

   Trip ID       Destination Start date   End date  Duration (days)  \
0        1        London, UK 2023-05-01 2023-05-08         0.222222
1        2  Phuket, Thailand 2023-06-15 2023-06-20         0.000000
2        3   Bali, Indonesia 2023-07-01 2023-07-08         0.222222
3        4     New York, USA 2023-08-15 2023-08-29         1.000000
4        5      Tokyo, Japan 2023-09-10 2023-09-17         0.222222

   Traveler name  Traveler age Traveler gender Traveler nationality  \
0     John Smith         0.375            Male             American
1       Jane Doe         0.200          Female             Canadian
2      David Lee         0.625            Male               Korean
3  Sarah Johnson         0.225          Female              British
4     Kim Nguyen         0.150          Female           Vietnamese

  Accommodation type  Accommodation cost Transportation type  \
0              Hotel            0.139241              Flight
1             Resort            0.088608              Flight
2              Villa            0.113924              Flight
3              Hotel            0.240506              Flight
4             Airbnb            0.075949               Train

   Transportation cost  Total Trip Cost
0             0.186441           1800.0
1             0.152542           1300.0
2             0.220339           1700.0
3             0.322034           3000.0
4             0.050847            900.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df_encoded = df_scaled.copy()

categorical_columns = [
    "Destination",
    "Traveler gender",
    "Traveler nationality",
    "Accommodation type",
    "Transportation type"
]

for col in categorical_columns:

    df_encoded[col] = encoder.fit_transform(
        df_encoded[col].astype(str)
    )

print(df_encoded.head())

In [ ]:
df_encoded = pd.get_dummies(
    df_scaled,
    columns=[
        "Destination",
        "Traveler gender",
        "Traveler nationality",
        "Accommodation type",
        "Transportation type"
    ],
    dtype=int
)

print(df_encoded.head())

In [ ]:
print(df_encoded.info())

In [ ]:
print(df_encoded.describe())

In [ ]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\ramas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\ramas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.18.0)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\ramas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\ramas\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (3.6.0)
Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Installing collected packages: joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.9.0

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\ramas\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip